package com.common.security.domain.model;

import java.io.Serializable;

/* Generated by Together */

public class Access implements Comparable<Access>,Serializable {
	private static final long serialVersionUID = -3790328375887043391L;

	private Integer resourceId;

	private String resourceName;

	private String resourceDescription;

	private Integer actionId;

	private String actionName;

	private String actionDescription;
	
	private Integer systemId;

	public Integer getActionId() {
		return actionId;
	}

	public void setActionId(Integer actionId) {
		this.actionId = actionId;
	}

	public String getActionName() {
		return actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	public Integer getResourceId() {
		return resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	public String getResourceName() {
		return resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	public String getAuthority() {
		return this.actionName + "-" + this.resourceName;
	}

	public String getActionDescription() {
		return actionDescription;
	}

	public void setActionDescription(String actionDescription) {
		this.actionDescription = actionDescription;
	}

	public String getResourceDescription() {
		return resourceDescription;
	}

	public void setResourceDescription(String resourceDescription) {
		this.resourceDescription = resourceDescription;
	}
	
	public Integer getSystemId() {
		return systemId;
	}

	public void setSystemId(Integer systemId) {
		this.systemId = systemId;
	}

	public int compareTo(Access arg0) {
		if (arg0 instanceof Access)
			return (""+((Access)arg0).resourceName+"-"+((Access)arg0).actionName).compareTo(""+resourceName+"-"+actionName);
		return -1;
	}

	@Override
	public String toString() {
		return actionName+"-"+resourceName;
	}
	
	
}