package com.common.security.domain.model;


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log extends PersistentObject {
	private static final long serialVersionUID = -7615052049454858414L;

	private Task task;

	private Date logdate;

	private String description;

	private Session session;

	public Date getLogdate() {
		return logdate;
	}

	public void setLogdate(Date logdate) {
		this.logdate = logdate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Task getTask() {
		return task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public Session getSession() {
		return session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

}
