package com.common.security.domain.model;

import java.util.HashSet;
import java.util.Set;

/* Generated by Together */

public class Role extends Temporal<Long> {
	private static final long serialVersionUID = 1L;

	/**
	 * @see Temporal.Attributes
	 */
	public interface Attributes extends Temporal.Attributes {
		public static final String SYSTEM = "system";
		public static final String PROFILE = "profile";
		public static final String ABBREVIATION = "abbreviation";
		public static final String NAME = "name";
		public static final String ACCESSES = "accesses";
	}

	private System system;

	private Profile profile;

	private String name;

	private String abbreviation;

	private Set<Access> accesses;

	public System getSystem() {
		return system;
	}

	public void setSystem(System system) {
		this.system = system;
	}

	public Profile getProfile() {
		return profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public String getAbbreviation() {
		return abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public Set<Access> getAccesses() {
		return accesses;
	}

	public void setAccesses(Set<Access> accesses) {
		this.accesses = accesses;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Access> accessControlList() {
		Set<Access> accessList = new HashSet<Access>();
		if (isValid()) {
			accessList.addAll(this.getAccesses());
		}
		return accessList;
	}
}
