package com.common.security.domain.model;

import java.util.HashSet;
import java.util.Set;

/* Generated by Together */

public class Role extends Temporal implements PermissionDefinition {

	private static final long serialVersionUID = -7147893864984323682L;

	private Set<Access> accesses;

	private String name;

	private String abbreviation;

	private System system;

	public String getAbbreviation() {
		return abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public Set<Access> getAccesses() {
		return accesses;
	}

	public void setAccesses(Set<Access> accesses) {
		this.accesses = accesses;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public System getSystem() {
		return system;
	}

	public void setSystem(System system) {
		this.system = system;
	}

	public Set<Access> accessControlList() {
		Set<Access> accessList = new HashSet<Access>();
		if (isValid()) {
			accessList.addAll(this.getAccesses());
		}
		return accessList;
	}
}
